### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'omic_sizes'

### ISSUE THREAD

**Issue by Tato14** [mahmoodlab/PORPOISE#9]
Thanks for the great tool. I am getting problems for running the different version of the model. If I do:

`python main.py --which_splits 5foldcv --split_dir SCLC --mode pathomic --reg_type pathomic --model_type porpoise_mmf --data_root_dir /Path/to/Extract_features/ --fusion bilinear --max_epochs 50`

Everything seems to work nicely. However if I remove `--model_type` I got an error on omic sizes:
```
****** Normalizing Data ******
training: 164, validation: 33
Genomic Dimension 10

Training Fold 0!

Init train/val/test splits... 
Done!
Training on 164 samples
Validating on 33 samples

Init loss function... Done!

Init Model... Traceback (most recent call last):
  File "main.py", line 258, in <module>
    results = main(args)
  File "main.py", line 76, in main
    val_latest, cindex_latest = train(datasets, i, args)
  File "/home/joan/PORPOISE/utils/core_utils.py", line 169, in train
    model_dict = {'fusion': args.fusion, 'omic_sizes': args.omic_sizes, 'n_classes': args.n_classes}
AttributeError: 'Namespace' object has no attribute 'omic_sizes'
```

I am not really getting why this is throwing an error. I see that `mcat` (default) uses this variable. I also got the error if I tried `--mode coattn` which also uses it. Is there anything related with the input data that I am missing? Thanks

**Comment by Link164735** [comment]
I also encountered this problem！

**Comment by Link164735** [comment]
> I also encountered this problem！
![image](https://github.com/mahmoodlab/PORPOISE/assets/106785653/999c0839-a902-48b7-aff9-fd38cded8155)

Maybe it's because **signatures=None**, but I didn't investigate further.
